version: "3.9"
    
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass