version: "3.9"
    
services:
  db:
    image: mysql:8
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass